# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run this workflow "At 18:00 UTC on Sunday and Saturday"
    # 对于定时任务,正常情况这个 workflow 一天运行一次也就够了,目前配置的是测试时间,因为不知道runner运行的实际时间段
    - cron: '20 9,13,19 * * 0,1,2,3,4,5,6'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17','21' ]
    steps:
    - name: setup maven
      uses: http://gitea.yunhorn.com/mirrors/setup-maven@v5
      with:
        maven-version: 3.8.8
    - uses: https://gitea.com/actions/checkout@v4
    - name: Set up JDK
      id: setup-java
      uses: https://gitea.com/actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
